import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserContextProvider } from "@/context/UserContext";
import { Header } from "@/components/Header";
import { FiltersContextProvider } from "@/context/FiltersContext";
import { CartContextProvider } from "@/context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  
  return (
    <html lang="en">
      <body className={`p-2 ${inter.className} h-screen`}>
        <UserContextProvider>
          <CartContextProvider>
            <Header />
            <FiltersContextProvider>
              <div className="mt-5 h-[calc(100vh-6rem)] overflow-auto">
                {children}
              </div>
            </FiltersContextProvider>
          </CartContextProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
